course_name = "模拟电子技术实验"
course_code = "EE1008"

notices = ""

[[lecturers]]
name = "实验中心教师+（部分班级）理论课教师+二名本科生助教"
[lecturers.author]
name = "Oliver Wu"
link = "https://github.com/OliverWu515"
date = ""

textbooks = []

[[online_resources]]
title = "OrCAD Cadence 16.6 软件资源"
url = "https://www.mr-wu.cn/"
description = "来自吴川斌的个人博客，站内搜索Cadence即可。"
[online_resources.author]
name = "Oliver Wu"
link = "https://github.com/OliverWu515"
date = ""

[[course]]
content = "实验报告在中国大学MOOC网上提交，无需提交纸质版。"
[course.author]
name = "Oliver Wu"
link = "https://github.com/OliverWu515"
date = ""

[[exam]]
content = """
分数构成：MOOC预习题 + 按时完成实验（不按时完成，则适当扣分）+ 报告分数。
没有考试。
"""
[exam.author]
name = "Oliver Wu"
link = "https://github.com/OliverWu515"
date = ""

[[advice]]
content = "老师会先讲一小会儿原理和注意事项（需要听一下，因为有些器材的使用方法不那么直观）。然后就自己做实验，有问题可以问助教。"
[advice.author]
name = "Oliver Wu"
link = "https://github.com/OliverWu515"
date = ""

[[advice]]
content = "对于硬件+仿真实验，有仿真预习，需要提前做好，上课需检查。仿真软件使用OrCAD Cadence 16.6。"
[advice.author]
name = "Oliver Wu"
link = "https://github.com/OliverWu515"
date = ""

[[advice]]
content = "对于含有硬件实验的项目，接线时务必注意电容接法、共地问题等。"
[advice.author]
name = "Oliver Wu"
link = "https://github.com/OliverWu515"
date = ""

[[advice]]
content = """
有MOOC预习题，答案整理中。不过十分建议大家先独立完成，其中一些基本概念比较重要。部分题目答案有问题，会标出。
"""
[advice.author]
name = "Oliver Wu"
link = "https://github.com/OliverWu515"
date = ""

[[schedule]]
content = """
（21级情况）前4个实验是2学时，实验5-实验7是4学时，最后一节4学时的课完成两个实验：实验8和实验9。
实验1-4、9为纯硬件实验，6-8为硬件+仿真实验，实验5为纯仿真实验。
"""
[schedule.author]
name = "Oliver Wu"
link = "https://github.com/OliverWu515"
date = ""

related_links = []

misc = []