course_name = "模拟电子技术实验"
course_code = "EE1008"

notices = """
对于硬件+仿真实验，有仿真预习，需要提前做好，上课需检查。仿真软件使用OrCAD Cadence 16.6，电路实验中已经使用过。
有MOOC预习题，答案整理中。不过十分建议大家先独立完成，其中一些基本概念比较重要。部分题目答案有问题，会标出。
实验报告在中国大学MOOC网上提交，无需提交纸质版。
"""

[[lecturers]]
name = "实验中心教师+理论课教师+本科生助教"
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

textbooks = []

online_resources = []

[[course]]
content = "实验1-4、9为纯硬件实验，6-8为硬件+仿真实验，实验5为纯仿真实验。"
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

exam = []

lab = []

[[advice]]
content = """老师会先讲一小会儿原理和注意事项（需要听一下，因为有些器材的使用方法不那么直观）。然后就自己做实验，有问题可以问助教。"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

[[advice]]
content = "对于含有硬件实验的项目，接线时务必注意电容接法、共地问题等。"
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

[[schedule]]
content = "（21级情况）前4个实验是2学时，实验5-实验7是4学时，最后一节4学时的课完成两个实验：实验8和实验9。"
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

[[related_links]]
content = "仿真软件OrCAD Cadence 16.6资源下载：https://www.mr-wu.cn/ (吴川斌的个人博客，站内搜索Cadence即可)"
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

misc = []