course_name = "模拟电子技术实验"
repo_type = "normal"
course_code = "EE1008"

# 授课教师 (Lecturers)
[[lecturers]]
name = "实验中心教师组"

  [[lecturers.reviews]]
  content = """授课教师：实验中心教师+（部分班级）理论课教师+二名本科生助教。"""
  author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

# 网络资源（电子书、网课等）
[[online_resources]]
title = "吴川斌的个人博客 (Cadence软件下载)"
url = "https://www.mr-wu.cn/"
description = "站内搜索 Cadence 即可。仿真软件使用 OrCAD Cadence 16.6，电路实验中已经使用过。"

# 核心课程评价区块
[[course]]
content = """
老师会先讲一小会儿原理和注意事项（需要听一下，因为有些器材的使用方法不那么直观）。
然后就自己做实验，有问题可以问助教。
"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

[[lab]]
content = """
（21级情况）前4个实验是2学时，实验5-实验7是4学时，最后一节4学时的课完成两个实验：实验8和实验9。
- 实验1-4、9为纯硬件实验，6-8为硬件+仿真实验，实验5为纯仿真实验。
- 对于硬件+仿真实验，有仿真预习，需要提前做好，上课需检查。
"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }

[[advice]]
content = """
有 MOOC 预习题，答案整理中。不过十分建议大家先独立完成，其中一些基本概念比较重要。部分题目答案有问题，会标出。
实验报告在中国大学 MOOC 网上提交，无需提交纸质版。
"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }
