course_name = "模拟电子技术实验"
repo_type = "normal"
course_code = "EE1008"

description = """
对于硬件+仿真实验，有仿真预习，需要提前做好，上课需检查。
对于含有硬件实验的项目，接线时务必注意电容接法、共地问题等。
"""

[[lecturers]]
name = "实验中心教师组(集体)"

[[lecturers.reviews]]
content = "授课教师：实验中心教师+（部分班级）理论课教师+二名本科生助教。"
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "" }


[[sections]]
title = "在线资源"

[[sections.items]]
content = "- [吴川斌的个人博客 (Cadence软件下载)](https://www.mr-wu.cn/)：站内搜索 Cadence 即可。仿真软件使用 OrCAD Cadence 16.6，电路实验中已经使用过。"


[[sections]]
title = "课程内容"

[[sections.items]]
content = """
老师会先讲一小会儿原理和注意事项（需要听一下，因为有些器材的使用方法不那么直观）。
然后就自己做实验，有问题可以问助教。
"""


[[sections]]
title = "关于实验"

[[sections.items]]
content = """
（21级情况）前4个实验是2学时，实验5-实验7是4学时，最后一节4学时的课完成两个实验：实验8和实验9。

- 实验1-4、9为纯硬件实验，6-8为硬件+仿真实验，实验5为纯仿真实验。
- 对于硬件+仿真实验，有仿真预习，需要提前做好，上课需检查。
"""


[[sections]]
title = "MOOC与作业"

[[sections.items]]
content = """
有 MOOC 预习题，答案整理中。不过十分建议大家先独立完成，其中一些基本概念比较重要。部分题目答案有问题，会标出。
实验报告在中国大学 MOOC 网上提交，无需提交纸质版。
"""
